//! The Rust half of the cross-implementation contract.
//!
//! This crate is emitted from the same `src/index.tish` as the JS bundle, so in principle it cannot
//! disagree with it. "In principle" is not a test. This runs the corpus in `conformance/` — the same
//! `.deck` inputs the JS build is checked against — and compares against the same expected parses,
//! which also exercises the one hand-written part of the crate (`facade.rs`).
//!
//! Regenerate the expected files in the deck repo with `npm run conformance:update`; never edit them
//! from this side.
use std::path::PathBuf;

fn corpus_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("conformance")
}

fn cases() -> Vec<String> {
    let mut out: Vec<String> = std::fs::read_dir(corpus_dir())
        .expect("conformance/ must ship with the crate")
        .filter_map(|e| e.ok())
        .filter_map(|e| e.file_name().into_string().ok())
        .filter(|n| n.ends_with(".deck"))
        .map(|n| n.trim_end_matches(".deck").to_string())
        .collect();
    out.sort();
    out
}

fn read(name: &str, ext: &str) -> String {
    let p = corpus_dir().join(format!("{name}.{ext}"));
    std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("{}: {e}", p.display()))
}

/// Field lookup on the expected JSON without pulling in serde: the expected files are generated by
/// `JSON.stringify(_, null, 2)`, so every scalar sits on its own predictably-indented line.
fn json_number(json: &str, path: &[&str]) -> Option<f64> {
    let mut rest = json;
    for (i, key) in path.iter().enumerate() {
        let needle = format!("\"{key}\":");
        rest = &rest[rest.find(&needle)? + needle.len()..];
        if i + 1 == path.len() {
            let val: String = rest
                .trim_start()
                .chars()
                .take_while(|c| c.is_ascii_digit() || *c == '-' || *c == '.')
                .collect();
            return val.parse().ok();
        }
    }
    None
}

fn json_count(json: &str, key: &str) -> usize {
    json.matches(&format!("\"{key}\":")).count()
}

#[test]
fn corpus_is_present_and_non_trivial() {
    let names = cases();
    assert!(
        names.len() >= 10,
        "expected the full corpus to ship with the crate, found {names:?}"
    );
}

/// The load-bearing test: every case parses, and the counts the expected file records line up with
/// what this crate produces. A grammar change on either side moves these apart.
#[test]
fn every_case_matches_the_expected_parse() {
    for name in cases() {
        let src = read(&name, "deck");
        let expected = read(&name, "expected.json");
        let program = deckfile::parse(&src);

        // `rawGenId` is track-only; `generatorId` also appears on every genBlock entry.
        let want_tracks = json_count(&expected, "rawGenId");
        assert_eq!(
            program.tracks.len(),
            want_tracks,
            "{name}: track count"
        );

        let want_errors = json_count(&expected, "msg");
        let got_errors: usize =
            program.errors.len() + program.tracks.iter().map(|t| t.body_errors.len()).sum::<usize>()
                + program.clips.iter().map(|c| c.body_errors.len()).sum::<usize>();
        assert_eq!(got_errors, want_errors, "{name}: error count");

        let want_directives = json_count(&expected, "verb");
        assert_eq!(
            program.directives.len(),
            want_directives,
            "{name}: directive count"
        );

        if let Some(bpm) = json_number(&expected, &["program", "bpm"]) {
            assert_eq!(program.bpm, Some(bpm), "{name}: bpm");
        }
    }
}

/// The specific divergences the corpus exists to pin, asserted directly so a failure names the bug
/// rather than just a count mismatch.
#[test]
fn pinned_divergences() {
    let p = deckfile::parse(&read("001-comments-and-sharps", "deck"));
    assert_eq!(p.scale_root, Some(6), "`scale F# minor` must survive comment stripping");
    assert_eq!(p.bpm, Some(120.0), "a trailing comment must still be stripped");
    assert_eq!(p.tracks[0].name, "C# Lead", "a `#` inside a token is data, not a comment");
    assert!(p.errors.is_empty());

    let p = deckfile::parse(&read("002-track-header", "deck"));
    let names: Vec<&str> = p.tracks.iter().map(|t| t.name.as_str()).collect();
    assert_eq!(
        names,
        ["MOS 6581", "Bass", "Pad", "Lead", "Layered", "Mixed"],
        "multi-word names"
    );
    assert_eq!(p.tracks[1].loop_bars, Some(2), "`* 2`");
    assert_eq!(p.tracks[2].loop_bars, None, "`* inf` clears the length, it is not an error");
    assert_eq!(p.tracks[3].gen_params.num("cutoff"), Some(1200.0), "macro param override");
    // `* N` after other params. This is the case that silently played at 1 bar instead of 16 and
    // made two of tish-gba's songs bake differently.
    assert_eq!(p.tracks[4].loop_bars, Some(16), "`* N` after a key/value pair");
    assert_eq!(p.tracks[4].gen_params.num("layer"), Some(0.0), "params survive alongside a late `* N`");
    assert_eq!(p.tracks[5].loop_bars, Some(4), "`* N` between key/value pairs");
    assert_eq!(p.tracks[5].gen_params.num("cutoff"), Some(900.0), "params on both sides of `* N`");

    let p = deckfile::parse(&read("003-steps-and-locks", "deck"));
    let steps = p.tracks[0]
        .body
        .iter()
        .find_map(|r| match r {
            deckfile::BodyRow::Steps { on, .. } => Some(on.len()),
            _ => None,
        })
        .expect("steps row");
    assert_eq!(steps, 16, "`|` separators are ignored, not counted as steps");
    let euclid_hits = p.tracks[1]
        .body
        .iter()
        .find_map(|r| match r {
            deckfile::BodyRow::Steps { on, euclid: true, .. } => Some(on.iter().filter(|b| **b).count()),
            _ => None,
        })
        .expect("euclid row");
    assert_eq!(euclid_hits, 5, "euclid fill is expanded by the package");
    assert!(
        p.tracks[2]
            .body
            .iter()
            .any(|r| matches!(r, deckfile::BodyRow::Loops { cap: None })),
        "`loops inf` is no cap, not an error"
    );

    let p = deckfile::parse(&read("004-notes", "deck"));
    let with_bar = p.tracks[0]
        .body
        .iter()
        .filter(|r| matches!(r, deckfile::BodyRow::Note { bar: Some(_), .. }))
        .count();
    assert_eq!(with_bar, 3, "`bar <selector>` must not be silently dropped");
    assert!(
        p.tracks[0].body.iter().any(|r| matches!(
            r,
            deckfile::BodyRow::Note { prob: Some(_), ratchet: Some(_), nudge: Some(_), lyric: Some(_), .. }
        )),
        "per-note locks survive"
    );

    let p = deckfile::parse(&read("009-directives", "deck"));
    assert_eq!(p.directives.len(), 8, "every `@` verb is collected");
    assert!(p.errors.is_empty(), "`@` directives must not produce errors");
    assert_eq!(p.bpm, Some(120.0), "a directive must not stop the rest of the parse");
}

/// Registries are module state living in a thread-local behind the emitted `pub fn`s. A host
/// registers at boot and parses afterwards, so state has to survive between calls.
#[test]
fn registries_persist_between_calls() {
    use tishlang_runtime::Value;

    deckfile::clearGeneratorIdAliases();
    deckfile::registerGeneratorIdAliases(
        Value::object_from_pairs([("noise_burst".into(), Value::String("noiseBurst".into()))]),
        Value::object_from_pairs([("noiseBurst".into(), Value::String("noise_burst".into()))]),
    );
    let p = deckfile::parse("track Kick id c0 gen noise_burst\n");
    assert_eq!(p.tracks[0].generator_id, "noiseBurst", "alias applies on a later call");
    assert_eq!(p.tracks[0].raw_gen_id, "noise_burst", "the deck spelling is preserved");

    deckfile::clearGeneratorIdAliases();
    let p = deckfile::parse("track Kick id c0 gen noise_burst\n");
    assert_eq!(
        p.tracks[0].generator_id, "noise_burst",
        "clear*() reassigns module state and the parser must see it"
    );
}
